version: 2.1
commands:
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: |
            npm install

jobs:
  ci-build:
    docker:
      - image: circleci/node:lts
    environment: 
      JEST_JUNIT_OUTPUT_DIR: test-output
    steps:
      - checkout 
      - install_deps
      - run:
          name: run tests
          command: |
            npm run unit-tests
            mkdir -p test-output
  integration-tests:
    docker:
      - image: circleci/node:lts
      - image: mongo:4.0
    environment:
      APP_PORT: 4000
    steps:
      - checkout
      - install_deps
      - run:
          name: run integration tests
          command: |
            npm run integration-tests
            mkdir -p test-output
  sast:
    docker:
      -image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Install NodeJsScan
          command: |
            sudo apt update
            sudo apt install python3-pip
            pip3 install nodejsscan
      -run:
          name: Run NodeJsScan
          command: |
            nodejsscan -d ./
  pack:
    docker:
      - image: circleci/node:lts
    environment:
      NODE_ENV: production
    steps:
      - checkout
      - install_deps
      - store_artifacts:
          path: ./

workflows:
  build-and-packge:
    jobs:
      - ci-build
      - integration-tests:
          requires:
            - ci-build
      - sast:
          requires:
            - ci-build
      - pack:
          requires:
            - ci-build
          filters:
            branches:
              only:
                - master
            